dist: trusty

language: go

go:
  - 1.9.*

services:
  - docker

install:
  - go get github.com/stretchr/testify 
  - travis_retry go get -d ./...
  - go build .
  - docker-compose up -d

script:
  - go test
  - cd test && go test
  